#!/bin/bash

[[ ! $1 ]] && { echo "missing argument" >&2; exit 1; }

scriptname="$1"
bindir="${HOME}/.bin"
filename="${bindir}/$scriptname"

[[ ! -e "$filename" ]] && { echo "no such command ${scriptname}" >&2; exit 1; }

read -p "are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  mv $filename "${bindir}/${scriptname}_$(date +%s)_deleted"
fi

exit 0;
